config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations', 
  passwords: 'users/passwords',
  registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/password', to: 'users/passwords#create'
    get '/users/sessions', to: 'users/sessions#index'
    root 'users/sessions#index'
  end
  
  
  
  resources :groups do
    resources :budgets, only: [:new, :create, :index, :destroy]
  end
  resources :users, only: [:index, :update, :destroy, :create]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/budget.rb
class Budget < ApplicationRecord

    belongs_to :user
   
    has_many :budgets_groups, dependent: :destroy
    has_many :groups, through: :budgets_groups
    validates :name, length: { maximum: 100 }, presence: { message: "The name field is mandatory" }
    validates :amount, length: { maximum: 100 }, presence: { message: "The name field is mandatory" }

end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: %i[ show edit update destroy ]

  # GET /budgets or /budgets.json
  def index
    @style = 'budgets/index'
    @budgets = BudgetsGroup.where(group_id: params[:group_id]).order(created_at: :desc)
    @groups =  Group.all
  end

  # GET /budgets/1 or /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @style = 'budgets/new'
    @budget = Budget.new
    @categories = Group.all
    @especific_group = params[:group_id]
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets or /budgets.json
 def create
    @budget = Budget.new(budget_params.merge(user_id: @current_user.id))
    
    respond_to do |format|
      if @budget.save
        @arraygroups = params[:categories]
        @arraygroups.each do |e|
          
          @budget_group = BudgetsGroup.new(budget_id: @budget.id, group_id: e)
        if @budget_group.save
          format.html { redirect_to group_budgets_path(params[:group_id]), notice: "Budget was successfully created." }
          format.json { render :show, status: :created, location: @budget }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @budget_group.errors, status: :unprocessable_entity }
        end
        end





      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1 or /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to budget_url(@budget), notice: "Budget was successfully updated." }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1 or /budgets/1.json
  def destroy
    @budget.destroy

    respond_to do |format|
      format.html { redirect_to group_budgets_path(params[:group_id]), notice: "Budget was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    

    def budget_params
      params.require(:budget).permit(:name, :amount,:group_id,:categories).slice(:name, :amount)
    end
    
    
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_budget.html.erb
<div class="transaction_item">
  
<div class="subtitle_head">
 <p>
    <%= budget.budget.name %>
  </p>
  <p class="price">
   $ <%= budget.budget.amount %>
  </p>
  </div>

  
  <div class="button_date">
  <p>
    <%= budget.budget.created_at.strftime("%y-%m-%d") %>
  </p>
  
  
  <%= button_to  group_budget_path(params[:group_id],:id => budget.budget.id), method: :delete, class: "nombre_de_la_clase", style: "background: none; border: none; text-decoration: underline;" do %>
  
    <%= image_tag "delete.png", size: "18x18"  %>
    <% end %>


</div>
  </div>
  

app/views/budgets/_form.html.erb
  <%= form_with(model: Budget.new, url: group_budgets_path(params[:group_id]), method: :post, class: 'form_new_budget') do |form| %>

  
  <header class="header_new">
  <%= link_to image_tag("back.png", class: "logo_budget") , group_budgets_path(:group_id => params[:group_id]), class: 'home_page'%>
  

  <h1 class="subtitle_new">New Transaction</h1>
  
  <div>
    <%= form.submit "Create", class: 'create_budget' %>
  </div>
  </header>
  
  <% if budget.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
        <% budget.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    
    <%= form.text_field :name , placeholder: '    Name'%>
  </div>

  <div>
    
    <%= form.text_field :amount, placeholder: '    $ 12.00' %>
  </div>
<h2 class="select_group">Select Groups</h2>
  <% comparative = @especific_group.to_i %>
<% @categories.each do |categories| %>
  
  <div class="form-check">
  
  <% cat = categories.id.to_i %>
  
  <% if cat == comparative %>

  <%= check_box_tag "categories[]", categories.id , true %>
    <%= label_tag "category_#{categories.id}", categories.name %>
    <% else %>
    <%= check_box_tag "categories[]", categories.id %>
    <%= label_tag "category_#{categories.id}", categories.name %>
    <% end %>

  </div>
<% end %>


  
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing budget</h1>

<%= render "form", budget: @budget %>

<br>

<div>
  <%= link_to "Show this budget", @budget %> |
  <%= link_to "Back to budgets", budgets_path %>
</div>

app/views/budgets/index.html.erb
<section class="section_budget_index">


<header class="header_new">


<%= link_to image_tag("back.png", class: "back_budget") ,  groups_path %>
<h1 class="subtitle_new">New Transaction</h1>
<%=  image_tag("search.png", class: "search")  %>
</header>
  




<div class="submount">
 <h2 class="hleft">Total Amount </h2> 
 <h3 class="hrigth"> $ <%= @budgets.sum {|p| p.budget.amount}  %> </h3>
 </div>


 <% @budgets.each do |budget| %>
  <div id="budgets">
  
  
  <%= render "budget",budget: budget %>
    


    </div>
  <% end %>
  <p style="color: green"><%= notice %></p>


</section>
<%= link_to  new_group_budget_path, class: 'button_add_budget' do%>
  <div class="add_button_budget">
  <%= image_tag "add.png",  class: 'boton_add'  ,size: "30x30" %>
  </div>
  <% end %>

app/views/budgets/new.html.erb
<section class="section_budgets_new">



<%= render "form", budget: @budget %>


</section>

app/views/budgets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @budget %>

<div>
  <%= link_to "Edit this budget", edit_budget_path(@budget) %> |
  <%= link_to "Back to budgets", budgets_path %>

  <%= button_to "Destroy this budget", @budget, method: :delete %>
</div>