config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations', 
  passwords: 'users/passwords',
  registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/password', to: 'users/passwords#create'
    get '/users/sessions', to: 'users/sessions#index'
    root 'users/sessions#index'
  end
  
  
  
  resources :groups do
    resources :budgets, only: [:new, :create, :index, :destroy]
  end
  resources :users, only: [:index, :update, :destroy, :create]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/group.rb
class Group < ApplicationRecord
    
belongs_to :user

has_many :budgets_groups , dependent: :destroy
has_many :budgets, through: :budgets_groups

validates :name, length: { maximum: 100 }, presence: { message: "The name field is mandatory" }
validates :icon, presence: { message: "The icon field is mandatory" }



    
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @style = 'groups/index'
    @groups =  Group.where(user_id: @current_user.id)
  end

  # GET /groups/1 or /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @style = 'groups/new'
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @style = 'groups/new'
    @group = Group.new(group_params.merge(user_id: @current_user.id))

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :icon)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, class: 'form_new_group') do |form| %>
  <header class="header_new">

<%= link_to image_tag("back.png", class: "logo_new") ,  groups_path , class: 'home_page'%>

<h1 class="subtitle_new">New category</h1>

<div>
    <%= form.submit "Create", class: 'create_category'%>
  </div>
</header>
  


    <%= form.text_field :name, placeholder: '    Name' %>
  

  
    
    <%= form.text_field :icon , placeholder: '    IMAGE URL "http//:image.png"'%>
  
  
<% end %>

<% if group.errors.any? %>
<div style="color: red">
  <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

  <ul>
    <% group.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/groups/_group.html.erb
<div class="content_category_item">

<%= link_to group_budgets_url(group_id: group.id), class: "category_content" do %>

  <div  class="item_horizontal">
<%= image_tag group.icon, class: 'items_category' %>


<div class="element_index">
<p>
   <%= group.name %>
</p>
  
<p>
    
    <% @sum = group.budgets.sum {|p| p.amount}  %>
    $ <%= @sum %>
  </p>
  </div>
  </div>
  
  <%end%>

  <%= button_to group_path(:id =>  group.id), method: :delete, class: "nombre_de_la_clase", style: "background: none; border: none; text-decoration: underline;" do %>
    <%= image_tag "delete.png", size: "25x25"  %>
    <% end %>
    
    </div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<section class="section_group_index">
<header class="header_groups_index">

<h3 class="categories_title" >Categories</h3>
<h1 class="sign_out">  <%= link_to image_tag("of.png", class: "logout") , destroy_user_session_path, method: :delete %> </h1>
</header>
<p style="color: green"><%= notice %></p>

  <div id="groups_index">
  <% @groups.each do |group| %>
    <%= render group %>
    <p>
      
    </p>
  <% end %>
  </div>

  </section>
  <%= link_to new_group_path do  %> 
    <div class="add_button">
    <%= image_tag "add.png",  class: 'boton_add'  ,size: "30x30" %>
    </div>
    <% end %>
    

app/views/groups/new.html.erb
<section class="section_group_new">


<%= render "form", group: @group %>



</section>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>