config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { confirmations: 'users/confirmations', 
  passwords: 'users/passwords',
  registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    get '/users/password', to: 'users/passwords#create'
    get '/users/sessions', to: 'users/sessions#index'
    root 'users/sessions#index'
  end
  
  
  
  resources :groups do
    resources :budgets, only: [:new, :create, :index, :destroy]
  end
  resources :users, only: [:index, :update, :destroy, :create]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/budgets_group.rb
class BudgetsGroup < ApplicationRecord
  belongs_to :group
  belongs_to :budget
end

app/controllers/budgets_groups_controller.rb
class BudgetsGroupsController < ApplicationController
  before_action :set_budgets_group, only: %i[ show edit update destroy ]

  # GET /budgets_groups or /budgets_groups.json
  def index
    @budgets_groups = BudgetsGroup.all
  end

  # GET /budgets_groups/1 or /budgets_groups/1.json
  def show
  end

  # GET /budgets_groups/new
  def new
    @budgets_group = BudgetsGroup.new
  end

  # GET /budgets_groups/1/edit
  def edit
  end

  # POST /budgets_groups or /budgets_groups.json
  def create
    @budgets_group = BudgetsGroup.new(budgets_group_params)

    respond_to do |format|
      if @budgets_group.save
        format.html { redirect_to budgets_group_url(@budgets_group), notice: "Budgets group was successfully created." }
        format.json { render :show, status: :created, location: @budgets_group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @budgets_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets_groups/1 or /budgets_groups/1.json
  def update
    respond_to do |format|
      if @budgets_group.update(budgets_group_params)
        format.html { redirect_to budgets_group_url(@budgets_group), notice: "Budgets group was successfully updated." }
        format.json { render :show, status: :ok, location: @budgets_group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @budgets_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets_groups/1 or /budgets_groups/1.json
  def destroy
    @budgets_group.destroy

    respond_to do |format|
      format.html { redirect_to budgets_groups_url, notice: "Budgets group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budgets_group
      @budgets_group = BudgetsGroup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def budgets_group_params
      params.require(:budgets_group).permit(:group_id, :budget_id)
    end
end

app/helpers/budgets_groups_helper.rb
module BudgetsGroupsHelper
end

app/views/budgets_groups/_budgets_group.html.erb
<div id="<%= dom_id budgets_group %>">
  <p>
    <strong>Group:</strong>
    <%= budgets_group.group_id %>
  </p>

  <p>
    <strong>Budget:</strong>
    <%= budgets_group.budget_id %>
  </p>
  
</div>

app/views/budgets_groups/_form.html.erb
<%= form_with(model: budgets_group) do |form| %>
  <% if budgets_group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(budgets_group.errors.count, "error") %> prohibited this budgets_group from being saved:</h2>

      <ul>
        <% budgets_group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :group_id, style: "display: block" %>
    <%= form.text_field :group_id %>
  </div>

  <div>
    <%= form.label :budget_id, style: "display: block" %>
    <%= form.text_field :budget_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/budgets_groups/edit.html.erb
<h1>Editing budgets group</h1>

<%= render "form", budgets_group: @budgets_group %>

<br>

<div>
  <%= link_to "Show this budgets group", @budgets_group %> |
  <%= link_to "Back to budgets groups", budgets_groups_path %>
</div>

app/views/budgets_groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Budgets groups</h1>

<div id="budgets_groups">
  <% @budgets_groups.each do |budgets_group| %>
    <%= render budgets_group %>
    <p>
      <%= link_to "Show this budgets group", budgets_group %>
    </p>
  <% end %>
</div>

<%= link_to "New budgets group", new_budgets_group_path %>

app/views/budgets_groups/new.html.erb
<h1>New budgets group</h1>

<%= render "form", budgets_group: @budgets_group %>

<br>

<div>
  <%= link_to "Back to budgets groups", budgets_groups_path %>
</div>

app/views/budgets_groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @budgets_group %>

<div>
  <%= link_to "Edit this budgets group", edit_budgets_group_path(@budgets_group) %> |
  <%= link_to "Back to budgets groups", budgets_groups_path %>

  <%= button_to "Destroy this budgets group", @budgets_group, method: :delete %>
</div>